# Generated by Django 3.2.7 on 2021-09-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isAvailable', models.BooleanField()),
                ('employee_id', models.CharField(max_length=100)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
