# Generated by Django 3.2.7 on 2021-09-27 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AssetManagement', '0002_alter_assets_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='status',
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('requestStatus', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('approved', 'approved')], default='pending', max_length=100)),
                ('assetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assets')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
