# Generated by Django 3.2.7 on 2021-09-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0003_auto_20210927_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
