# Generated by Django 3.2.7 on 2021-09-27 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0004_alter_assets_isavailable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('requestId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='description',
            field=models.CharField(default='description', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='requestId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
