# Generated by Django 3.2.7 on 2021-09-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0005_auto_20210927_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetrequest',
            old_name='approved_date',
            new_name='updated_date',
        ),
    ]
