# Generated by Django 3.2.7 on 2021-09-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0006_rename_approved_date_assetrequest_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='requestStatus',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
