# Generated by Django 3.2.7 on 2021-09-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0009_alter_employee_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
