# Generated by Django 3.2.7 on 2021-09-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0010_auto_20210928_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrequest',
            name='requestId',
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
