# Generated by Django 3.2.7 on 2021-09-29 02:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0011_auto_20210929_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='requestId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
