# Generated by Django 3.2.7 on 2021-09-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0012_auto_20210929_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='requestStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
