# Generated by Django 3.2.8 on 2021-10-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0014_assets_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='isAvailable',
        ),
    ]
